#
# BTstack example 'hid_host_demo' for ESP32 port
#
# Generated by C:/msys32/home/Akinori/btstack/port/esp32
# On 06/16/19 01:30:27

PROJECT_NAME := hid_host_demo

include $(IDF_PATH)/make/project.mk
